server:
  host: "0.0.0.0"
  port: 8080
  max_connections: 100

database:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "admin"
  password: "password"
  database_name: "test_db"

logging:
  level: "INFO"
  file: "/var/log/server.log"
  max_size: "10MB"
  max_backup: 5

features:
  enable_auth: true
  enable_cache: false
  enable_ssl: true
  allowed_ips:
    - "192.168.1.100"
    - "192.168.1.101"